In [4]:
pip install pandas

Requirement already satisfied: pandas in c:\users\reshu\appdata\local\programs\python\python312\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\reshu\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\reshu\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\reshu\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\reshu\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd

In [7]:
data={'name':['alice','bob'],'age':[25,30]}

In [10]:
df=pd.DataFrame(data)

In [11]:
lst=[['alice',25],['bob',30]]

In [12]:
df=pd.DataFrame(lst,columns=['name','age'])

In [13]:
df.head()

    name  age
0  alice   25
1    bob   30

In [14]:
df.tail()

    name  age
0  alice   25
1    bob   30

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      str
 1   age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [16]:
df.describe()

             age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [17]:
df['name']

0    alice
1      bob
Name: name, dtype: str

In [18]:
df[['name','age']]

    name  age
0  alice   25
1    bob   30

In [19]:
df.loc[0]

name    alice
age        25
Name: 0, dtype: object

In [20]:
df.iloc[1]

name    bob
age      30
Name: 1, dtype: object

In [21]:
df[df['age']>25]

  name  age
1  bob   30

In [22]:
df['gender']=['f','m']

In [23]:
df.drop('age',axis=1,inplace=True)

In [24]:
df.isnull()

    name  gender
0  False   False
1  False   False

In [25]:
df.dropna()

    name gender
0  alice      f
1    bob      m

In [28]:
df.fillna(0)

    name gender
0  alice      f
1    bob      m

In [42]:
df1=pd.DataFrame({'key':['A','B','C'],'V1':[1,2,3]})
df2=pd.DataFrame({'key':['A','B','D'],'V2':[4,5,6]})

In [43]:
pd.merge(df1,df2,on='key')

  key  V1  V2
0   A   1   4
1   B   2   5

In [45]:
df1.join(df2,lsuffix='_left',rsuffix='_right')

  key_left  V1 key_right  V2
0        A   1         A   4
1        B   2         B   5
2        C   3         D   6

In [3]:
import os

In [4]:
os.getcwd()

'C:\\Users\\RESHU\\Desktop\\AIML'

In [7]:
df=pd.read_csv('data.csv')

In [8]:
df.to_csv('output.csv',index=False)

In [9]:
df.sort_values('age')

    name  age
0  alice   25
1    bob   30

In [10]:
df['age'].apply(lambda x:x+1)

0    26
1    31
Name: age, dtype: int64

In [11]:
df['name'].unique()

<StringArray>
['alice', 'bob']
Length: 2, dtype: str

In [12]:
df['age'].value_counts()

age
25    1
30    1
Name: count, dtype: int64